SELECT username FROM all_users;

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER  scott
IDENTIFIED BY tiger
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;
 
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE
TO scott;


SELECT * FROM tab;

SELECT * FROM dba_users
ORDER BY username;

SELECT *
FROM dba_users
WHERE username = 'SCOTT';

ALTER USER scott ACCOUNT UNLOCK;