SELECT username FROM all_users;

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER  scott
IDENTIFIED BY tiger
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;
 
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE
TO scott;