SELECT username FROM all_users ORDER BY username;

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER scott
IDENTIFIED BY tiger
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, CREATE VIEW, UNLIMITED TABLESPACE
TO scott;

CREATE USER  hr
IDENTIFIED BY hr
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;
 
--권한 주기
GRANT CONNECT, RESOURCE, CREATE VIEW, UNLIMITED TABLESPACE
TO hr;

GRANT CREATE VIEW TO scott;


SELECT * FROM tab;

SELECT * FROM dba_users
ORDER BY username;

SELECT *
FROM dba_users
WHERE username = 'SCOTT';

ALTER USER scott ACCOUNT UNLOCK;